global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-service"
    static_configs:
      - targets:
          - "api-service:8001"
  
  - job_name: "data-fetch-service"
    static_configs:
      - targets:
          - "data-fetch-service:8002"
