{
 "title": "API Monitoring (data-fetch-service)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(api_request_duration_seconds_bucket{job=\"data-fetch-service\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_request_duration_seconds_bucket{job=\"data-fetch-service\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_request_duration_seconds_bucket{job=\"data-fetch-service\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average API Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(api_request_duration_seconds_sum{job=\"data-fetch-service\"}[1m])) by (endpoint, method) /\nsum(rate(api_request_duration_seconds_count{job=\"data-fetch-service\"}[1m])) by (endpoint, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Errors per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, method, status) (rate(api_errors_total{job=\"data-fetch-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(endpoint, method, status) (rate(api_requests_total{job=\"data-fetch-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}