# @title Get Best Combination
POST {{API_URL}}/graphql
Content-Type: application/json

{
  "query": "query GetBestCombination($teams: [String!]!, $opts: FetchOptions) { getBestCombination(teams: $teams, opts: $opts) { status data { packages combinedMonthlyPriceCents combinedMonthlyPriceYearlySubscriptionInCents coverage } } }",
  "variables": {
    "teams": ["Deutschland", "FC Barcelona", "Frankreich", "FC Salzburg", "RB Leipzig"],
    "opts": {
      "limit": 3
    }
  }
}