name: frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        working-directory: frontend
        uses: actions/checkout@v3

      - name: Set up Node.js
        working-directory: frontend
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        working-directory: frontend
        run: npm install -g pnpm

      - name: Install dependencies using pnpm
        working-directory: frontend
        run: pnpm install

      - name: Run Prettier and auto-format for backend
        working-directory: frontend
        run: pnpm prettier --check "**/*.{js,jsx,ts,tsx,astro,html}"

      - name: Build project
        working-directory: frontend
        run: pnpm run build
