name: frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/iron'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies using pnpm
        working-directory: ./frontend
        run: pnpm install

      - name: Run Prettier 
        working-directory: ./frontend
        run: pnpm run format:check

      - name: Build project
        working-directory: ./frontend
        run: pnpm run build
