name: frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/iron'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies using pnpm
        working-directory: frontend
        run: pnpm install

      - name: Build project
        working-directory: frontend
        run: pnpm run build
