name: mongodb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-mongodb:
    runs-on: ubuntu-latest

    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start MongoDB with docker-compose
        run: docker-compose -f docker-compose.yaml up -d mongodb

      - name: Wait for MongoDB initialization to complete
        run: |
          for i in {1..20}; do
            if docker logs mongodb 2>&1 | grep -q "MongoDB initialization complete"; then
              echo "MongoDB initialization complete"
              break
            fi
            echo "Waiting for MongoDB initialization to complete..."
            docker-compose logs mongodb
            sleep 5
          done

          # If the loop didn't break, fail the CI step
          if ! docker logs mongodb 2>&1 | grep -q "Creating index for bc_streaming_package..."; then
            echo "MongoDB did not complete initialization within the expected time."
            exit 1
          fi

      - name: Cleanup
        run: docker-compose -f docker-compose.yaml down
