name: mongodb

on:
  push:
    branches: [ "main" ]
    paths:
      - "mongodb/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "mongodb/**"

jobs:
  test-mongodb:
    runs-on: ubuntu-latest

    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start MongoDB with docker-compose
        run: docker-compose -f docker-compose.yaml up -d mongodb

      - name: Wait for MongoDB initialization to complete
        run: |
          for i in {1..20}; do
            if docker logs mongodb 2>&1 | grep -q "MongoDB initialization complete"; then
              echo "MongoDB initialization complete"
              break
            fi
            echo "Waiting for MongoDB initialization to complete..."
            sleep 5
          done

          # If the loop didn't break, fail the CI step
          if ! docker logs mongodb 2>&1 | grep -q "Creating index for bc_streaming_package..."; then
            echo "MongoDB did not complete initialization within the expected time."
            docker-compose logs mongodb
            exit 1
          fi

      - name: Verify collections and document counts
        run: |
          bc_game_count=$(docker exec mongodb mongosh best_combination --quiet --eval "db.bc_game.countDocuments()")
          bc_streaming_offer_count=$(docker exec mongodb mongosh best_combination --quiet --eval "db.bc_streaming_offer.countDocuments()")
          bc_streaming_package_count=$(docker exec mongodb mongosh best_combination --quiet --eval "db.bc_streaming_package.countDocuments()")

          echo "bc_game count: $bc_game_count"
          echo "bc_streaming_offer count: $bc_streaming_offer_count"
          echo "bc_streaming_package count: $bc_streaming_package_count"

          [[ "$bc_game_count" -eq 8871 ]] || { echo "bc_game count mismatch"; exit 1; }
          [[ "$bc_streaming_offer_count" -eq 32439 ]] || { echo "bc_streaming_offer count mismatch"; exit 1; }
          [[ "$bc_streaming_package_count" -eq 37 ]] || { echo "bc_streaming_package count mismatch"; exit 1; }

      - name: Cleanup
        run: docker-compose -f docker-compose.yaml down
