name: mongodb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-mongodb:
    runs-on: ubuntu-latest

    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start MongoDB with docker-compose
        run: docker-compose -f docker-compose.yaml up -d mongodb

      - name: Log MongoDB collections and counts
        run: |
          docker exec mongodb mongosh best_combination --quiet --eval "db.getCollectionNames().forEach(c => print(c + ': ' + db[c].countDocuments()))"

      - name: Cleanup
        run: docker-compose -f docker-compose.yaml down
