name: rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, beta, nightly]
        service: [best_combination_api, best_combination_worker, data_fetch, libs]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install Clippy
        run: rustup component add clippy

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Build
        working-directory: ./apps/${{ matrix.service }}
        run: cargo build --verbose
      
      - name: Run Clippy (Linting)
        working-directory: ./apps/${{ matrix.service }}
        run: cargo clippy -- -D warnings

      - name: Check Code Formatting
        working-directory: ./apps/${{ matrix.service }}
        run: cargo fmt --all --check

      - name: Run Tests
        working-directory: ./apps/${{ matrix.service }}
        run: cargo test --verbose -- --test-threads=1

      - name: Run Tests in Release Mode
        working-directory: ./apps/${{ matrix.service }}
        run: cargo test --release --verbose -- --test-threads=1
