name: rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, beta, nightly]
        service: [best_combination_api, best_combination_worker, data_fetch, libs]
      fail-fast: false

    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start MongoDB with docker-compose
        run: docker-compose -f docker-compose.yaml up -d mongodb

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install Clippy
        run: rustup component add clippy

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Build
        working-directory: ./apps/${{ matrix.service }}
        run: cargo build --verbose
      
      - name: Run Clippy (Linting)
        working-directory: ./apps/${{ matrix.service }}
        run: cargo clippy -- -D warnings

      - name: Check Code Formatting
        working-directory: ./apps/${{ matrix.service }}
        run: cargo fmt --all --check

      - name: Run Tests
        working-directory: ./apps/${{ matrix.service }}
        run: cargo test --verbose -- --test-threads=1

      - name: Run Tests in Release Mode
        working-directory: ./apps/${{ matrix.service }}
        run: cargo test --release --verbose -- --test-threads=1
